[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 921600
lib_deps =
    sparkfun/SparkFun Qwiic 6Dof - LSM6DSO
    links2004/WebSockets
build_flags =
    -D USE_MAHONY_FILTER
